#!/bin/bash

# Quick deployment helper script

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║           Nouakchott Places - Deployment Helper             ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "Initializing git repository..."
    git init
    git add .
    git commit -m "Initial commit: Nouakchott Places Manager"
    echo "✅ Git repository initialized"
    echo ""
fi

echo "📝 Your deployment options:"
echo ""
echo "1. 🚀 Render (Recommended - Free, Always Online)"
echo "   → https://render.com"
echo "   → Create Web Service from GitHub repo"
echo "   → Start command: python app.py"
echo ""
echo "2. 🌐 Railway (Also Free)"
echo "   → https://railway.app"
echo "   → Deploy from GitHub repo (auto-detects)"
echo ""
echo "3. ⚡ ngrok (Quick Temporary Link)"
echo "   → Run: brew install ngrok"
echo "   → Then: ngrok http 5000"
echo "   → Share the URL (valid for 2 hours)"
echo ""
echo "4. 🐍 PythonAnywhere"
echo "   → https://www.pythonanywhere.com"
echo "   → Free Python hosting"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 Files ready for deployment:"
echo "   ✅ Procfile (tells servers how to run)"
echo "   ✅ requirements.txt (Python dependencies)"
echo "   ✅ runtime.txt (Python version)"
echo "   ✅ app.py (updated for cloud deployment)"
echo ""
echo "🔗 Next steps:"
echo ""
echo "1. Create GitHub repo:"
echo "   git remote add origin https://github.com/YOUR-USERNAME/nouakchott-places.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "2. Go to Render.com or Railway.app"
echo "3. Connect your GitHub repo"
echo "4. Deploy! ✨"
echo ""
echo "📖 Full guide: See DEPLOYMENT.md"
echo ""
echo "⚠️  IMPORTANT: Add authentication before deploying!"
echo "   See DEPLOYMENT.md for instructions"
echo ""
